-- Roommate Hub schema for PostgreSQL 15+ / Supabase.
-- Run this file in Supabase Dashboard -> SQL Editor.

BEGIN;

DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS blocked_users CASCADE;
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS contact_permissions CASCADE;
DROP TABLE IF EXISTS viewing_appointments CASCADE;
DROP TABLE IF EXISTS match_requests CASCADE;
DROP TABLE IF EXISTS room_posts CASCADE;
DROP TABLE IF EXISTS user_preferences CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    gender VARCHAR(10) NOT NULL CHECK (gender IN ('MALE', 'FEMALE', 'OTHER')),
    phone VARCHAR(20),
    avatar_url VARCHAR(1000),
    birth_date DATE,
    university VARCHAR(150),
    role VARCHAR(20) NOT NULL DEFAULT 'ROLE_USER'
        CHECK (role IN ('ROLE_ADMIN', 'ROLE_USER')),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'LOCKED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    target_district VARCHAR(100) NOT NULL,
    budget_amount DOUBLE PRECISION NOT NULL,
    sleep_habit INTEGER NOT NULL CHECK (sleep_habit BETWEEN 1 AND 3),
    cleanliness_level INTEGER NOT NULL CHECK (cleanliness_level BETWEEN 1 AND 5),
    is_smoking BOOLEAN NOT NULL DEFAULT FALSE,
    allow_pets BOOLEAN NOT NULL DEFAULT FALSE,
    bio_description TEXT
);

CREATE TABLE room_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    price DOUBLE PRECISION NOT NULL CHECK (price >= 0),
    address VARCHAR(255) NOT NULL,
    district VARCHAR(100),
    deposit DOUBLE PRECISION CHECK (deposit IS NULL OR deposit >= 0),
    electricity_water_cost DOUBLE PRECISION
        CHECK (electricity_water_cost IS NULL OR electricity_water_cost >= 0),
    area DOUBLE PRECISION CHECK (area IS NULL OR area >= 0),
    max_occupants INTEGER NOT NULL DEFAULT 2 CHECK (max_occupants > 0),
    current_occupants INTEGER NOT NULL DEFAULT 0 CHECK (current_occupants >= 0),
    amenities VARCHAR(500),
    image_url VARCHAR(1000),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('AVAILABLE', 'PENDING', 'APPROVED', 'REJECTED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (current_occupants <= max_occupants)
);

CREATE TABLE match_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    match_score DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (sender_id, receiver_id),
    CHECK (sender_id <> receiver_id)
);

CREATE TABLE viewing_appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    host_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    room_post_id BIGINT NOT NULL REFERENCES room_posts(id) ON DELETE CASCADE,
    appointment_time TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED')),
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE contact_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    granted_to_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    match_request_id BIGINT NOT NULL REFERENCES match_requests(id) ON DELETE CASCADE,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, granted_to_id)
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_id BIGINT NOT NULL,
    target_type VARCHAR(20) NOT NULL CHECK (target_type IN ('USER', 'ROOM_POST')),
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'RESOLVED', 'DISMISSED')),
    action_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE blocked_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blocked_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, blocked_user_id)
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    receiver_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    image_url VARCHAR(1000),
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_room_posts_price ON room_posts(price);
CREATE INDEX idx_room_posts_district ON room_posts(district);
CREATE INDEX idx_room_posts_status_created ON room_posts(status, created_at DESC);
CREATE INDEX idx_match_requests_receiver ON match_requests(receiver_id);
CREATE INDEX idx_appointments_host_time ON viewing_appointments(host_id, appointment_time);
CREATE INDEX idx_chat_messages_sender_receiver ON chat_messages(sender_id, receiver_id, created_at);

COMMIT;
